name: Provision of Ec2 instance and configuration with Ansible 

on:
   push:
       branches:
              - main 

jobs:
    Provision_ec2:
      runs-on: ubuntu-latest

      steps:
        - name: checkout repo
          users: actions/checkout@v2

        - name: Setup Python 3.x
          users: actions/Setup-python@v2 
          with:
             python-version: "3.10"

        - name: Install dependenies
          run: |
            python -m pip install --upgrade pip
            pip install ansible boto3
            ansible-galaxy collection install amazon.aws
                        